# Generated by Django 4.2.2 on 2024-06-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('services', models.CharField(choices=[('Project Management', 'Project Management'), ('Building Construction', 'Building Construction'), ('Renovation and Remodeling', 'Renovation and Remodeling'), ('Demolition', 'Demolition'), ('Site Preparation', 'Site Preparation'), ('Electrical Work', 'Electrical Work'), ('Plumbing', 'Plumbing'), ('HVAC', 'HVAC'), ('Roofing', 'Roofing'), ('Flooring', 'Flooring'), ('Painting and Decorating', 'Painting and Decorating'), ('Carpentry', 'Carpentry'), ('Masonry', 'Masonry'), ('Landscaping', 'Landscaping'), ('Insulation', 'Insulation'), ('General Repairs', 'General Repairs'), ('Property Maintenance', 'Property Maintenance'), ('Pest Control', 'Pest Control'), ('Cleaning Services', 'Cleaning Services'), ('Handyman Services', 'Handyman Services'), ('Architectural Design', 'Architectural Design'), ('Engineering Services', 'Engineering Services'), ('Interior Design', 'Interior Design'), ('Environmental Consulting', 'Environmental Consulting'), ('Safety Consulting', 'Safety Consulting'), ('Green Building', 'Green Building'), ('Historical Restoration', 'Historical Restoration'), ('Waterproofing', 'Waterproofing'), ('Fireproofing', 'Fireproofing'), ('Security Systems', 'Security Systems'), ('Emergency Repairs', 'Emergency Repairs'), ('Disaster Recovery', 'Disaster Recovery'), ('Permitting and Inspections', 'Permitting and Inspections'), ('Material Procurement', 'Material Procurement'), ('Logistics and Transportation', 'Logistics and Transportation')], max_length=255)),
                ('years_experience', models.PositiveIntegerField()),
            ],
        ),
    ]
